FROM node:20-alpine

WORKDIR /app

ARG NPM_TOKEN
RUN echo "@muhamed-mustafa:registry=https://npm.pkg.github.com/" >> .npmrc \
 && echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc

COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src
COPY tools ./tools

RUN npm install && rm .npmrc

EXPOSE 4001

CMD ["npm", "run", "dev"]
