name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./microservices/jobber-shared
        run: npm install

      - name: Build package
        working-directory: ./microservices/jobber-shared
        run: npm run build

      - name: Create .npmrc for GitHub Packages auth
        working-directory: ./microservices/jobber-shared
        run: |
          echo "@muhamed-mustafa:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        working-directory: ./microservices/jobber-shared
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
